### PR TITLE
Add minimum required Python version

### PR DESCRIPTION
**Pull request by Rotzbua**
## Change

* Add minimum required Python version
* Add test for every alive Python version (except broken 3.12)

### CODE REVIEW

**Comment by JohannesBuchner** [comment]
what causes this change? for both.

**Comment by JohannesBuchner** [comment]
What is the oldest python version we can support? I think it is driven by the requirements, not this package.

**Comment by Rotzbua** [comment]
The oldest version is python 3.8. Everything else is EOL:
https://devguide.python.org/versions/

**Comment by Rotzbua** [comment]
> what causes this change? for both.

`pip` supports proper dependency resolution. For this it needs the supported Python versions.
Good programming paradigm: only claim to support something when it is tested.

**Comment by JohannesBuchner** [comment]
I am closing this because it is not properly justified.

Firstly, just because the Python project does not provide support for older versions, does not mean imagehash is incompatible.

Second, passing tests is a requirement for compatible versions, but there may be compatible versions beyond the tests currently set up. We also do not test all patch versions of python, yet assume they are compatible.

Imagehash is pure python code. The compatibility is introduced by dependencies. We do not need to document these dependencies here, because pip will look them up as needed.

There is a cost associated to testing "all" or a large number of python versions, namely a carbon footprint on the computing center for every git push. It seems to me we do not gain substantial information here by testing intermediate versions over testing the earliest and latest supported python version.

**Pull request closed without merging**
