### PR TITLE
Update __init__.py

### PR DESCRIPTION
**Pull request by fxolivia**
for dhash, the file you followed http://www.hackerfactor.com/blog/index.php?/archives/529-Kind-of-Like-That.html, when you did the 3rd step that computing the difference, it said that the 9 pixels per row yields 8 differences between adjacent pixels. thus, if you print out the pixels,in my opinion, it should be a 8*9 matrix, right?

### CODE REVIEW

**Comment by JohannesBuchner** [comment]
The parameter hash_size defines the desired hash size, e.g. 9x9. 

dhash makes an image that is 10x9 to accomodate.

**Comment by fxolivia** [comment]
ahash
dhash
program_result
I don't know whether I explained clear or not. when you calculate the difference of DHASH, you compare with different rows, but the file you followed calculated diffrence based on whether the left pixel is brighter than right pixel. And the image size is 9*8, it means width is 9, height is 8, I make a notation in the figure.

**Comment by JohannesBuchner** [comment]
I see it now, thank you. I opened issue #28.

**Comment by JohannesBuchner** [comment]
Could you try out the newest version of the code?

**Pull request closed without merging**
