### PR TITLE
Image scale assert bugfix

### PR DESCRIPTION
**Pull request by dmpetrov**

### CODE REVIEW

**Comment by JohannesBuchner** [comment]
I think you still need a rounding to integer in there, otherwise it doesn't do anything.

**Comment by JohannesBuchner** [comment]
You can draw some inspiration from 
http://www.exploringbinary.com/ten-ways-to-check-if-an-integer-is-a-power-of-two-in-c/
https://code.activestate.com/recipes/577514-chek-if-a-number-is-a-power-of-two/

**Comment by dmpetrov** [comment]
Thank you for the comment. You are right. This is doesn't work in general.
Replaced to bitwise checking.

**Comment by JohannesBuchner** [comment]
What about 

assert hash_size == 2**level, "hash_size is not power of 2"

**Comment by dmpetrov** [comment]
Oh.. thank you for noticing. Commited.

**Comment by JohannesBuchner** [comment]
Hmm, there may be some more bugs hidden in there. 
Could you create a script test_whash.py (similar to https://github.com/JohannesBuchner/imagehash/blob/master/test.py) which test your whash function, varying each parameter so that all cases are tested?

**Comment by dmpetrov** [comment]
The test file was added. Note that I imported unittest lib.

The code works perfect for filters which scale the image as power of 2, including default 'haar' filter. However, some filters might have different formula for the low level frequency area size. For today we can:
1) keep power-of-two asserts, then we have a (small) chance of firing the asserts even when all pre-conditions satisfy and hash might be created
2) just remove the asserts, pywt exceptions will clearly indicate a problem part

The current change implements (1), but we can switch to (2).

Johannes, how do you think?

**Comment by dmpetrov** [comment]
Added a link to a wHash blog post in this pull request.

**Comment by dmpetrov** [comment]
Hi Johannes, could you please merge this change? This is an important change with a bug fix.

And if possible, could you please change whash links in  pypi website to my blog post (https://fullstackml.com/2016/07/02/wavelet-image-hash-in-python/) instead of the Kaggle competition web page? People are asking for this: https://www.kaggle.com/c/avito-duplicate-ads-detection/forums/t/22011/precomputed-wavelet-image-hashes/126567#post126567

**Comment by JohannesBuchner** [comment]
I rewrote the commit into a single commit, but with the same content and under your name. You might need to re-clone your github repo.

**Comment by JohannesBuchner** [comment]
Thank you for the fixes!

**Comment by dmpetrov** [comment]
Johannes, thank you!

**Pull request closed without merging**
