### PR TITLE
Do not read version from file for pyinstaller compatibility

### PR DESCRIPTION
**Pull request by mastergenius**
Pyinstaller do not add VERSION file to distribution and module import fails

### CODE REVIEW

**Comment by JohannesBuchner** [comment]
Could you describe the problem you are trying to solve here?

**Comment by mastergenius** [comment]
We bundle tool which uses imagehash using pyinstaller. Pyinstaller do not add file VERSION to resulting bundle, so we receive exception when importing imagehash (can't open file).

**Comment by JohannesBuchner** [comment]
I understand that this solved your problem, however this PR does not seem like an adequate general solution, as it breaks imagehash.__version__ completely.

It seems that you need to create a specs file and specify the datas if data files should be bundled with a package: https://pythonhosted.org/PyInstaller/spec-files.html#using-spec-files

**Comment by TysonLinger** [comment]
I encountered the same issue between imagehash and pyinstaller. Adding imagehash's VERSION file to datas didn't fix the problem. I resorted to doing the same thing as mastergenius in order to get it to work. If anyone knows of a better solution please let me know.

**Comment by jmvermeulen** [comment]
This issue is still active, i fixed it by including the VERSION file explicitly in the .spec.
Small hack but it works.
 
```
a = Analysis(['main.py'],
                    ("venv/Lib/site-packages/imagehash/VERSION", "imagehash/")
```

**Comment by JohannesBuchner** [comment]
I think I should solve this with something like `bumpversion`

**Comment by JohannesBuchner** [comment]
I think this is solved in the latest version(s). Please reopen if you find it is still an issue.

**Pull request closed without merging**
