### PR TITLE
Updated linting configs

### PR DESCRIPTION
**Pull request by Avasam**
While working on #167 I found it quite annoying that autofixes were changing so much at once. And that I had to ignore quite a lot of linting errors.

So I've isolated type hint changes in #167 and linting changes here. This contains missing configuration and all changes necessary for all linting to pass and be picked-up by the editor.

### CODE REVIEW

**Comment by JohannesBuchner** [comment]
The preferred indentation style in this project is tabs, otherwise this looks good.

**Comment by Avasam** [comment]
> The preferred indentation style in this project is tabs, otherwise this looks good.

There was a mix so I wasn't sure and went with defaults. Gotcha I'll update it!

**Comment by JohannesBuchner** [comment]
Yes, I was lenient on contributed code (mostly tests).

**Comment by Avasam** [comment]
@JohannesBuchner Would you like me to set prefered quotes as well? (single vs double) https://pypi.org/project/flake8-quotes/

**Comment by JohannesBuchner** [comment]
> @JohannesBuchner Would you like me to set prefered quotes as well? (single vs double) https://pypi.org/project/flake8-quotes/

No, I don't really care.

**Comment by JohannesBuchner** [comment]
I'm curious, what tool did you use to make the code confirm to the flake8 rules?

**Comment by Avasam** [comment]
> I'm curious, what tool did you use to make the code confirm to the flake8 rules?

Autopep8 is the autofixer used here for pycodestyle (and isort for imports). Another popular (more complete, but opinionated with few configurations) is [black](https://pypi.org/project/black/)

**Comment by Avasam** [comment]
Coverage decrease probably caused by new line returns in uncovered code.

**Comment by JohannesBuchner** [comment]
Thanks a lot @Avasam!

**Pull request merged**
