### PR TITLE
fix link rot since doamin `blockhash.io` is expired

### PR DESCRIPTION
**Pull request by n0099**

### CODE REVIEW

**Comment by JohannesBuchner** [comment]
Thank you!

**Comment by SpangleLabs** [comment]
What's the point linking to it as an alternate project if it has been deleted though?

**Comment by n0099** [comment]
idk

**Comment by JohannesBuchner** [comment]
maybe we should link to https://github.com/commonsmachinery/blockhash-python instead

**Comment by n0099** [comment]
LGTM

**Comment by JohannesBuchner** [comment]
feel free to make another PR if you care about this

**Pull request merged**
