### PR TITLE
#164: replaced deprecated `Image.ANTIALIAS` with `Image.Resampling.LANCZOS`

### LINKED ISSUE #164: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead

### PR DESCRIPTION
**Pull request by lene**
Closes #164

### CODE REVIEW

**Comment by JohannesBuchner** [comment]
Does this patch lead to compatible behaviour over different versions of Pillow?

**Comment by Avasam** [comment]
> Does this patch lead to compatible behaviour over different versions of Pillow?

Probably not because of the Pillow version specifier that was added.
This should probably instead dynamically check for the installed pillow version in code then use the appropriate image resampling constant. As simple as:
```py
from PIL import Image, __version__
__PIL_VERSION = tuple(map(int, __version__.split('.')))
if __PIL_VERSION >= (9, 1):
  _RESAMPLING = Image.Resampling.LANCZOS
else:
  _RESAMPLING = Image.ANTIALIAS
```

**Comment by JohannesBuchner** [comment]
I am worried that if someone uses imagehash with some version of pillow, and now reinstalls imagehash with this PR applied, that the previously computed hashes do not match the same images any more, if the aliasing behaviour is different.

That's why I am wondering: is there is a pillow flag which brings back the exact aliasing behaviour of Image.ANTIALIAS?

**Comment by JohannesBuchner** [comment]
https://pillow.readthedocs.io/en/stable/deprecations.html suggests that it is a rename

two users provided anecdotes that the behaviour is the same:
https://www.reddit.com/r/learnpython/comments/uxb8b4/help_pillow_deprecation_warning/

**Comment by JohannesBuchner** [comment]
I don't like the version checks, we should minimize this as much as possible, in favor of behaviour checks.

Maybe something like:
```
try:
    ANTIALIAS = Image.Resampling.LANCZOS
except AttributeError:
    ANTIALIAS = Image.ANTIALIAS
```

**Comment by Avasam** [comment]
> I don't like the version checks, we should minimize this as much as possible, in favor of behaviour checks.
> 
> Maybe something like:
> 
> ```
> try:
>     ANTIALIAS = Image.Resampling.LANCZOS
> except AttributeError:
>     ANTIALIAS = Image.ANTIALIAS
> ```

Oh yeah that's much better. Sometimes I forget that exceptions are totally valid for flow control in Python.

**Comment by JohannesBuchner** [comment]
This is fixed in master.

**Pull request closed without merging**
