### PR TITLE
File string instead of pil.Image object as argument

### PR DESCRIPTION
**Pull request by sophiawisdom**
Added support for giving file string instead of Image object

### CODE REVIEW

**Comment by ohld** [comment]
Really usefull

**Comment by williamwisdom** [comment]
@JohannesBuchner will this PR ever get merged?

**Comment by JohannesBuchner** [comment]
This PR is in need of tests to increase the coverage, and documentation of the feature.

**Comment by JohannesBuchner** [comment]
I prefer to keep a clear interface without overloading of the parameter types.

**Pull request closed without merging**
