### PR TITLE
Fix script for Python3

### PR DESCRIPTION
**Pull request by bjlittle**
@JohannesBuchner This PR fixes the script `find_similar_images.py` so that it works in Python3.

Closes #29

### CODE REVIEW

**Comment by bjlittle** [comment]
@JohannesBuchner How exactly is the `find_similar_images.py` script distributed i.e. if I do a `python setup.py install --user` the script is not installed ... where do you intend this script to be installed?

Also, there is no test coverage? Should there be?

**Comment by bjlittle** [comment]
@JohannesBuchner I noticed that when you updated `pypi` with version `3.1` you never updated the `CHANGELOG` in the `README.rst` ... was that a genuine omission?

**Comment by JohannesBuchner** [comment]
I think tests for this scripts are not essential -- not sure if it is even possible to test it, one would have to set up a directory with multiple files. How complicated can travis-ci test get? I have another project that relies on building a Fortran library first with cmake, would that also be possible? travis-ci seems to use some virtual machines, doesn't it?

Yes, I did not bother to add a note to the Changelog, the changes were more incremental from a user perspective. Maybe I summarise them at 4.0.

**Comment by bjlittle** [comment]
@JohannesBuchner What's your other project? Does it live on github?

Travis-ci does fire up virtual environments so its pretty cheap and efficient to use and totally customisable. What are you trying to do?

**Comment by JohannesBuchner** [comment]
I have https://github.com/JohannesBuchner/PyMultiNest/ which is a Python wrapper for another program: https://github.com/JohannesBuchner/MultiNest, which I did not write. That library is to be built with cmake, then one has to set LD_LIBRARY_PATH to use it with PyMultiNest. It would increase my confidence if travis-ci could automatically check whether a change still works (Python2&3, perhaps different Linux/Mac versions), but I am not sure this is possible because of the binary-dependence.

**Comment by bjlittle** [comment]
@JohannesBuchner Looks pretty interesting. 

Let me see if I understand ... Is it that you want to test that the python wrapper interface to the underlying MultiNest library is stable and correct given a change to either the wrapper or the library or both? i.e. testing that both the wrapper and the library need are in sync.

Travis is triggered on a PR, so is it right that if the underlying library changes, you then need a PR to update the wrapper to keep it in sync and mirror the library change. Therefore Travis is active on the wrapper report only ... Is that right?

**Comment by JohannesBuchner** [comment]
The library will not change often, so yes, the test would be on the wrapper. The wrapper should work for the current version and a few earlier versions. In the most fancy setup, I would like to test whether the entire stack works on Linux and Mac. At least I would like to test when I change something whether the wrapper still works fine with the library. That library+wrapper is used by many astronomers.

**Comment by bjlittle** [comment]
@JohannesBuchner Okay, I think that this might be reasonably straight forward. I notice that you've tagged releases of the library https://github.com/JohannesBuchner/MultiNest/releases which is pretty handy (infact, I'm pretty keen for you to do the same with `imagehash` please).

My suggestion is that we can make MultiNest available on conda-forge, then in the travis-ci for the wrapper, simply install the specific tagged version of MultiNest from conda-forge in the travis-ci conda test environment and test with the PR wrapper code. We can use travis-ci to have a matrix of several test builds against the versions of MultiNest that you care about, say `v2.14`, `v2.13` and `v2.12`.

I'd target building on Linux first just to see if everything hangs together. Then perhaps condider how to rinse-and-repeat on OSX.

I don't know when I might get time to do this, but would you be keen for me to give it a try ... ?

**Comment by JohannesBuchner** [comment]
That all sounds great and would be very useful! I added tags to imagehash back to 2.0.

The library has no tests, but includes some minimal example programs in various languages (C, Fortran, C++). 
The wrapper has several demo programs. https://github.com/JohannesBuchner/PyMultiNest/blob/master/pymultinest_solve_demo.py should be easy enough to transform into a test, for example that evidence is between 235 and 237, and the error below 0.5.

**Pull request merged**
