### PR TITLE
Speed optimization for whash

### PR DESCRIPTION
**Pull request by samzhang111**
PR for #57

### CODE REVIEW

**Comment by JohannesBuchner** [comment]
If I remember correctly, treating PIL images as arrays was introduced at some later point, so with this patch we might lose compatibility with older PIL versions?

**Comment by samzhang111** [comment]
It was introduced during Pillow 1.1.6: http://effbot.org/zone/pil-changes-116.htm. That came out in 2006.

It's a significant enough speedup that if we're worried about older versions of PIL we could set a flag for versions of PIL >= 1.1.6 and only treat the image as an array if it meets the version requirements.

**Comment by JohannesBuchner** [comment]
Hmm, okay, if it is so long ago and classic PIL seems to be more or less unused, I am okay with your proposed change. I will do a major version bump then.
Could you do the same for the other functions as well?

**Comment by samzhang111** [comment]
I think I did that in above commit. It's been a month though and I forget. Can you see if this is mergeable?

**Comment by JohannesBuchner** [comment]
Thank you for the patch!

**Pull request merged**
