### PR TITLE
Extend hex_to_hash capability.

### PR DESCRIPTION
**Pull request by bjlittle**
This PR extends the capability of `imagehash.hex_to_hash` to copy with different hash sizes.

### CODE REVIEW

**Comment by JohannesBuchner** [comment]
Thank you! Would you be interested in making the module python3 compatible?

**Comment by bjlittle** [comment]
@JohannesBuchner Awesome, thanks! :beers: 

I'm **really** interested in `imagehash`. I'd love to make several changes to move imagehash forwards, if you're happy for me to do that?

We can aim for pk3, as there will be appetite in the community for that. I'd also like to increase the test coverage, automate the testing with travis-ci, add some automated test coverage stats, and ultimately push this repo on to conda-forge.

If you're actively eyeballing `imagehash`, then i'll start iterating over the code base and push PRs when I get the time ... does that sound like a plan?

Did you want to take `imagehash` in any particular direction? What are your plans/thoughts?

**Comment by JohannesBuchner** [comment]
Increasing test coverage sounds good.
Running tests in an automated fashions sounds good. Unfortunately I have not much experience with the available tools and services.

If you want to make changes, that's great. I would ask you to not change the code style, and to make one change per pull request/commit.

I think one of the reasons imagehash is popular is that it is minimalistic and very short code that can be easily understood and adapted. I would like to keep it minimalistic and KISS (i.e. not turning it into a framework and adding more dependencies).

Otherwise you can of course fork the project and run with it.

What is pk3?

**Comment by bjlittle** [comment]
@JohannesBuchner Great, that sounds perfect ... and I'm all for keeping things simple, so I'm totally on board with you there.

Apologies, didn't mean to confuse, but by pk3, I meant python3.

BTW when are you going to push to the latest master to pypi? That would be super handy from my point of view :smile:

**Comment by JohannesBuchner** [comment]
I would want the code to work both in python2 and python3. There is also another pull request you can have a look at, trying to replace iteritems with items in the demo (but unfortunately it does some other things at the same time).
I would push the code when I am certain it has been tested well :) Writing and running some unit tests against that function would be consistent with what you have planned.

**Comment by bjlittle** [comment]
@JohannesBuchner Do you have a preference for `unittest` or `pytest`?

I'm a heavy user of `unittest`, so that's easy for me, but if you prefer `pytest` (or another test framework) that would be good to know ...

**Comment by JohannesBuchner** [comment]
I usually just use nose which does not require any modules in the code. See test.py
But test_whash.py already uses unittest, so you could use that if you need setup-test-teardown or specific assert methods. Actually the class in that file could be simplified to functions I believe?

**Pull request merged**
