### PR TITLE
Added hex_to_multihash to recover saved ImageMultiHash

### PR DESCRIPTION
**Pull request by seemanne**
This PR adds hex_to_multihash which recovers an ImageMultiHash object after being cast with str()
This would also solve #160 by offering a method to recover saved crop-resistant hashes.

### CODE REVIEW

**Comment by JohannesBuchner** [comment]
Please add some tests for this, including one from scratch and a round-trip one.

**Comment by seemanne** [comment]
> Please add some tests for this, including one from scratch and a round-trip one.

Could you clarify what you mean with "from scratch" in this case?  
I will add one that goes ImageMultiHash -> string -> ImageMultiHash for the round trip

**Comment by JohannesBuchner** [comment]
By "from scratch" I mean a test that contains a hardcoded string from which the ImageMultiHash object is created.

**Comment by JohannesBuchner** [comment]
This PR should also be updated to the latest version

**Comment by seemanne** [comment]
agreed, I will merge with new upstream, Is the test ok this way or should I do even directer hardcode similar to how it is done in test_hex_conversions.py

**Comment by JohannesBuchner** [comment]
Yes, the latter, something like https://github.com/JohannesBuchner/imagehash/blob/master/tests/test_hash_is_constant.py#L41

You can first generate the hashes using an example image offline, then copy their string representation into the test.

**Comment by JohannesBuchner** [comment]
Thanks a lot!

If you are motivated, #73 and #113 are similar small issues.

**Pull request merged**
