### PR TITLE
Improve speed for arr to hex and hex to arr conversions.

### PR DESCRIPTION
**Pull request by IDDT**
As the title says.

```
import numpy as np
from imagehash import _binary_array_to_hex, _binary_array_to_hex_old
from imagehash import hex_to_hash, hex_to_hash_old
import timeit
import random


test_arrays = [np.random.rand(8, 8) > np.full((8,8), 0.5) for i in range(100)]
all([_binary_array_to_hex(x) == _binary_array_to_hex_old(x) for x in test_arrays])
#True
%timeit [_binary_array_to_hex(x) for x in test_arrays]
#3.41 ms ± 66.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
%timeit [_binary_array_to_hex_old(x) for x in test_arrays]
#5.47 ms ± 102 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


hexes = [_binary_array_to_hex_old(x) for x in test_arrays]
all([hex_to_hash(x) == hex_to_hash_old(x) for x in hexes])
#True
%timeit [hex_to_hash(x) for x in hexes]
#2.13 ms ± 33.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
%timeit [hex_to_hash_old(x) for x in hexes]
#3.72 ms ± 38.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

### CODE REVIEW

**Comment by szymonk92** [comment]
That would be a great improvement. @JohannesBuchner  could you push it?

**Comment by woctezuma** [comment]
Very nice!

**Comment by JohannesBuchner** [comment]
Could you please remove the 3 added/removed empty lines from the PR?

Is this change fully backward-compatible (in its string representation)?

**Comment by IDDT** [comment]
Random array generation and then comparing the results of new and old functions didn't show any issues, I'm unaware of any edge cases where the results might diverge.

**Comment by bigcat88** [comment]
Hello to all. Maybe i am wrong(not a pro in python code, only omw to that goal).
`bin(int(hexstr, 16))[2:]` - it will cut all start zeroes.
For example int hash of size 8: 
00f0f0f0f8f8f8f8
Result will be: 11110000111100001111000011111000111110001111100011111000 = 56 bits instead of 64.

Correct me if i didnt notice any moment.

**Comment by IDDT** [comment]
@bigcat88 good catch! `.zfill(hash_size**2)` seems to do the job.

**Comment by bigcat88** [comment]
@IDDT Thanks.
I have another proposal, look at this pseudo code:
`1d_array_of_uint8 = numpy.frombuffer(bytes.fromhex(hexstr), dtype=numpy.uint8)`
`1d_array_of_bits = numpy.unpackbits(1d_array_of_uint8, axis=None)`
`here some code to reshape array in two dimensions`

You can test it, and see  results yourself.
I didnt test it myself(i modified imagehash too far, and store hashes as bytes, that why cant test), but it will work.

**Comment by JohannesBuchner** [comment]
Could you please add a few (~20) random test cases for various hash sizes produced from the original code to the test harness, and make sure that the tests reproduce them. Maybe it should be a separate PR. Then we can be safe to merge this PR.

We need both directions (arr to hex and hex to arr) separately.

**Comment by JohannesBuchner** [comment]
The suggested tests would also make me more confident about PR https://github.com/JohannesBuchner/imagehash/pull/113

**Pull request closed without merging**
